### PR TITLE
[CP] Katello 4.10.0 CP for version 1.10.0

### PR DESCRIPTION
**Pull request by lfu**
hammer_cli_katello version has been bumped to 1.10.0.

### CODE REVIEW

**Comment by ianballou** [comment]
Is hammer still complaining about the missing `.mo` files? If so, wonder if we could fix that as part of this CP.  @chris1984 might know how to fix it when he's back

**Comment by ianballou** [comment]
I'm guessing the CP is fine if it was clean

**Comment by lfu** [comment]
> Is hammer still complaining about the missing `.mo` files? 

Don't see that.

**Comment by ianballou** [comment]
> > Is hammer still complaining about the missing `.mo` files?
> 
> Don't see that.

Gotcha, on master right now there are warnings about the `.mo` files being out of date when you run any command. If there are no warnings, then this should be good to merge

**Comment by ianballou** [comment]
@parthaa do you wanna take a quick look since this is your PR that's CP'd in?

**Review by jeremylenz — APPROVED** [review]

**Pull request merged**
