### PR TITLE
refs #18964 - registry name pattern

### PR DESCRIPTION
**Pull request by thomasmckay**
Requires https://github.com/Katello/katello/pull/7262

### CODE REVIEW

**Comment by akofink** [comment]
There's a rubocop failure.

**Comment by thomasmckay** [comment]
@akofink - Any idea on the failed tests? I rebased on master.

**Comment by akofink** [comment]
https://github.com/Katello/hammer-cli-katello/pull/567

**Comment by akofink** [comment]
@thomasmckay Please remove your apipie cache (I generated one that includes this change in #567) and rebase.

**Comment by akofink** [comment]
@thomasmckay please see my previous comment. Let's get this merged.

**Comment by akofink** [comment]
@thomasmckay what's going on here?

**Comment by akofink** [comment]
10 more days have passed. This PR is really close to ready for merge, just remove the apipie cache and rebase.

**Comment by akofink** [comment]
Ping @thomasmckay If no response, I'm going to close this.

**Comment by akofink** [comment]
Closing! Feel free to reopen with requested changes.

**Pull request closed without merging**
