### PR TITLE
Fixes #27523 - removing options from ContentView update

### PR DESCRIPTION
**Pull request by sseelam2**
This PR was created to remove repositories, product-id and product from `hammer content-view update --help`

### CODE REVIEW

**Comment by chris1984** [comment]
Thanks @sseelam2 will start to test

**Comment by chris1984** [comment]
@sseelam2 

I am still seeing the repo flag in my --help with the patch applied to my hammer devel box

```bash
[vagrant@centos7-hammer-devel hammer-cli-katello]$ hammer content-view list
----------------|---------------------------|---------------------------|-----------|---------------------|---------------
CONTENT VIEW ID | NAME                      | LABEL                     | COMPOSITE | LAST PUBLISHED      | REPOSITORY IDS
----------------|---------------------------|---------------------------|-----------|---------------------|---------------
1               | Default Organization View | Default_Organization_View |           | 2019/08/05 14:06:45 |               
2               | Zoo                       | Zoo                       |           | 2019/08/05 14:18:19 | 1, 2          
----------------|---------------------------|---------------------------|-----------|---------------------|---------------
[vagrant@centos7-hammer-devel hammer-cli-katello]$ hammer content-view update --help
Usage:
    hammer content-view update [OPTIONS]

Options:
 --auto-publish AUTO_PUBLISH             Enable/Disable auto publish of composite view
                                         One of true/false, yes/no, 1/0.
 --component-ids COMPONENT_IDS           List of component content view version ids for composite views
                                         Comma separated list of values. Values containing comma should be quoted or escaped with backslash.
                                         JSON is acceptable and preferred way for complex parameters
 --description DESCRIPTION               Description for the content view
 --id ID                                 Content view identifier
 --name NAME                             Content view name to search by
 --new-name NEW_NAME                     New name for the content view
 --organization ORGANIZATION_NAME        Organization name to search by
 --organization-id ORGANIZATION_ID       Organization ID to search by
 --organization-label ORGANIZATION_LABEL Organization label to search by
 --repository-ids REPOSITORY_IDS         List of repository ids
                                         Comma separated list of values. Values containing comma should be quoted or escaped with backslash.
                                         JSON is acceptable and preferred way for complex parameters
 --solve-dependencies SOLVE_DEPENDENCIES Solve RPM dependencies by default on Content View publish, defaults to false
                                         One of true/false, yes/no, 1/0.
 -h, --help                              Print help
```

**Comment by chris1984** [comment]
@akofink ah ok, thanks for clearing it up. When working with @sseelam2 I thought we were removing all references of repos, but yeah that makes sense

**Comment by sseelam2** [comment]
> Requesting changes, as this will also need to happen with `content-view create`

I'm on it @akofink

**Comment by chris1984** [comment]
@sseelam2 is this good to retest? I see a new push since the last review.

**Comment by sseelam2** [comment]
@chris1984 Yes, It's up for retesting. I made the requested changes.

**Comment by chris1984** [comment]
Looks good :) Thanks @sseelam2 

Content View Update:

```bash
[vagrant@centos7-hammer-devel ~]$ hammer content-view update --help
Usage:
    hammer content-view update [OPTIONS]

Options:
 --auto-publish AUTO_PUBLISH             Enable/Disable auto publish of composite view
                                         One of true/false, yes/no, 1/0.
 --component-ids COMPONENT_IDS           List of component content view version ids for composite views
                                         Comma separated list of values. Values containing comma should be quoted or escaped with backslash.
                                         JSON is acceptable and preferred way for complex parameters
 --description DESCRIPTION               Description for the content view
 --id ID                                 Content view identifier
 --name NAME                             Content view name to search by
 --new-name NEW_NAME                     New name for the content view
 --organization ORGANIZATION_NAME        Organization name to search by
 --organization-id ORGANIZATION_ID       Organization ID to search by
 --organization-label ORGANIZATION_LABEL Organization label to search by
 --repository-ids REPOSITORY_IDS         List of repository ids
                                         Comma separated list of values. Values containing comma should be quoted or escaped with backslash.
                                         JSON is acceptable and preferred way for complex parameters
 --solve-dependencies SOLVE_DEPENDENCIES Solve RPM dependencies by default on Content View publish, defaults to false
                                         One of true/false, yes/no, 1/0.
 -h, --help                              Print help
```

Content View Create:

```bash
[vagrant@centos7-hammer-devel ~]$ hammer content-view create --help
Usage:
    hammer content-view create [OPTIONS]

Options:
 --auto-publish AUTO_PUBLISH             Enable/Disable auto publish of composite view
                                         One of true/false, yes/no, 1/0.
 --component-ids COMPONENT_IDS           List of component content view version ids for composite views
                                         Comma separated list of values. Values containing comma should be quoted or escaped with backslash.
                                         JSON is acceptable and preferred way for complex parameters
 --composite                             Create a composite content view
 --description DESCRIPTION               Description for the content view
 --label LABEL                           Content view label
 --name NAME                             Name of the content view
 --organization ORGANIZATION_NAME        Organization name to search by
 --organization-id ORGANIZATION_ID       Organization ID
 --organization-label ORGANIZATION_LABEL Organization label to search by
 --repository-ids REPOSITORY_IDS         List of repository ids
                                         Comma separated list of values. Values containing comma should be quoted or escaped with backslash.
                                         JSON is acceptable and preferred way for complex parameters
 --solve-dependencies SOLVE_DEPENDENCIES Solve RPM dependencies by default on Content View publish, defaults to false
                                         One of true/false, yes/no, 1/0.
 -h, --help                              Print help
```

**Pull request merged**
