### PR TITLE
0.22.3 cherry-picks and version bump

### PR DESCRIPTION
**Pull request by ianballou**
@chris1984 do I need to do anything with the foreman_api.json ?

### CODE REVIEW

**Comment by chris1984** [comment]
@ianballou only if travis fails, if it does I will send you the steps to create a new one.

**Comment by chris1984** [comment]
@ianballou looks like you need this guy too:

https://github.com/Katello/hammer-cli-katello/commit/b1d9a4d3eccd18d397948d3bf0a2758e44de583d

Do you want me to make a redmine for it, or are you cool just bringing it in. the change is on the hammer-cli-foreman side of things but makes the tests pass based on their removal of the compute attributes

**Comment by ianballou** [comment]
@chris1984 I'm okay with just picking it in.

**Review by chris1984 — APPROVED** [review]
APJ

**Pull request merged**
