### PR TITLE
Refs #21768 - allow nil searchables

### PR DESCRIPTION
**Pull request by mbacovsky**
https://github.com/theforeman/hammer-cli-foreman/pull/346 brings some incompatible and test braking changes. This patch is fixing the tests and commands that were obviously broken by the changes.

For testing it is necessary to use hammer-cli master, latest apipie-bindings (0.2.2), hammer-cli-foreman with https://github.com/theforeman/hammer-cli-foreman/pull/346, and foreman with https://github.com/theforeman/foreman/pull/4917 (merged a few weeks ago).

### CODE REVIEW

**Comment by mbacovsky** [comment]
Updated to match changes in hammer-cli-foreman.

**Comment by mbacovsky** [comment]
@akofink, is there anything I can do to make the review easier? I'd like to get this to GA so the sooner it is in the more time we have to find the problem.

**Comment by mbacovsky** [comment]
@akofink, thanks! I'll trigger the tests here once hammer-cli-foreman is merged.

**Comment by tstrachota** [comment]
FYI https://github.com/theforeman/hammer-cli-foreman/pull/346 has been merged.

**Comment by akofink** [comment]
I've restarted the build.

**Comment by akofink** [comment]
Rubocop issues here

**Pull request merged**
