### PR TITLE
Refs #36237 - add host info and update count totals on ak show

### PR DESCRIPTION
**Pull request by chris1984**
Needs https://github.com/Katello/katello/pull/10499

* Check out Hammer PR:
* Create an activation key
* Register a host with an activation key
* Run hammer activation-key info --id X and see if it shows the associated host
* Set a limit on your key and see if it shows how many more times it can be used

### CODE REVIEW

**Review by sjha4 — COMMENTED** [review]
Tested with updated activation keys API:

Able to see hosts in the activation key details with hammer. ✔️ 
Able to see new formatted host limit in the format : Consumed of Host_limit ✔️ 

Screenshot from 2023-04-05 09-34-14

I am concerned about one thing here. If there are hundreds of hosts attached to an activation_key, the output may become unreadable. Should we provide an option to show hosts in the info here and not show them by default? Does that make sense?

**Comment by chris1984** [comment]
> Tested with updated activation keys API:
> 
> Able to see hosts in the activation key details with hammer. ✔️ Able to see new formatted host limit in the format : Consumed of Host_limit ✔️
> 
> Screenshot from 2023-04-05 09-34-14
> 
> I am concerned about one thing here. If there are hundreds of hosts attached to an activation_key, the output may become unreadable. Should we provide an option to show hosts in the info here and not show them by default? Does that make sense?

Yeah that makes sense, let me see what I can do with it.

**Comment by chris1984** [comment]
@sjha4 updated if you want to try again. pass in `--show-hosts` to see the hosts on the key

**Comment by chris1984** [comment]
@sjha4 updated

Without hosts param:
```
[vagrant@hammer ~]$ hammer activation-key show --id 1
Name:                  Custom
Id:                    1
Host Limit:            1 of Unlimited
Auto Attach:           true
Lifecycle Environment: Library
Content View:          Default Organization View
Host Collections:

Content Overrides:

System Purpose:
    Service Level:
    Purpose Usage:
    Purpose Role:
    Purpose Addons:
```

With hosts param:
```
[vagrant@hammer ~]$ hammer activation-key show --show-hosts true --id 1
Name:                  Custom
Id:                    1
Host Limit:            1 of Unlimited
Auto Attach:           true
Lifecycle Environment: Library
Content View:          Default Organization View
Associated Hosts:
 1) Id:   1
    Name: devel.croberts.io
Host Collections:

Content Overrides:

System Purpose:
    Service Level:
    Purpose Usage:
    Purpose Role:
    Purpose Addons:
```

**Review by sjha4 — APPROVED** [review]
Works great 👍🏼

**Pull request merged**
