### PR TITLE
Fixes #31117 - Add content-export list/version for pulp 3 export

### PR DESCRIPTION
**Pull request by chris1984**
This PR adds the ability to do a content view version export with the new export API for Pulp 3.

```shell
[vagrant@hammer hammer-cli-katello]$ hammer content-export version --id 2 --destination-server food2
[...............................................................................................................................................................................................................................] [100%]

[vagrant@hammer hammer-cli-katello]$ hammer content-export export-histories
---|--------------------|----------------------------------------------------------------------------------|----------------------|-------------------------|-------------------------|------------------------
ID | DESTINATION SERVER | PATH                                                                             | CONTENT VIEW VERSION | CONTENT VIEW VERSION ID | CREATED AT              | UPDATED AT             
---|--------------------|----------------------------------------------------------------------------------|----------------------|-------------------------|-------------------------|------------------------
1  | tascioni           | /var/lib/pulp/exports/Default_Organization/view/1.0/tascioni/2020-11-02T21-19... | view 1.0             | 2                       | 2020-11-02 21:19:20 UTC | 2020-11-02 21:19:20 UTC
2  | food               | /var/lib/pulp/exports/Default_Organization/view/1.0/food/2020-11-03T17-28-45-... | view 1.0             | 2                       | 2020-11-03 17:28:48 UTC | 2020-11-03 17:28:48 UTC
3  | food2              | /var/lib/pulp/exports/Default_Organization/view/1.0/food2/2020-11-03T17-30-16... | view 1.0             | 2                       | 2020-11-03 17:30:20 UTC | 2020-11-03 17:30:20 UTC
---|--------------------|----------------------------------------------------------------------------------|----------------------|-------------------------|-------------------------|------------------------
```

### CODE REVIEW

**Comment by parthaa** [comment]
Basic export is  workgin good. Some functionality needs to get added to this PR

- This call should fetch the export-history status after the export has been completed and get the path and metadata json for this history and create $path/metadata.json .

- If the path does not exist (pulp + foreman in different box, have it generated in the /tmp/{tmpdir}/metadata.json)

**Comment by jturel** [comment]
Be sure to rename this PR+commit to reflect the changes accurately :)

**Comment by chris1984** [comment]
> Be sure to rename this PR+commit to reflect the changes accurately :)

Yep, this was just a temp/draft name so Partha could see why the code and look at the test

**Review by parthaa — APPROVED** [review]
Works well. ACK

**Comment by parthaa** [comment]
> Be sure to rename this PR+commit to reflect the changes accurately :)

Going to 2nd that. Change the commit message before merging to reflect
```
$ hammer content-export list
--|------------------------|----------------------------------------------------------------------------------|----------------------|-------------------------|-------------------------|------------------------
ID | DESTINATION SERVER     | PATH                                                                             | CONTENT VIEW VERSION | CONTENT VIEW VERSION ID | CREATED AT              | UPDATED AT             
---|------------------------|----------------------------------------------------------------------------------|----------------------|-------------------------|-------------------------|------------------------
1  | downstream.example.com | /var/lib/pulp/exports/export-16876/view/1.0/downstream.example.com/2020-10-23... | view 1.0             | 3                       | 2020-10-23 01:17:44 UTC | 2020-10-23 01:17:44 UTC
2  | downstream.example.com | /var/lib/pulp/exports/export-16876/view/1.0/downstream.example.com/2020-10-23... | view 1.0             | 3                       | 2020-10-23 01:49:11 UTC | 2020-10-23 01:49:11 UTC

$ hammer content-export version --id=4 --destination-server=two.com
[.....................................................................................................................................................................................................................................] [100%]
Generated /var/lib/pulp/exports/export-16876/view/2.0/two.com/2020-11-18T02-16-30-00-00/metadata.json
```

**Pull request merged**
