### PR TITLE
Run the tests for default rake task

### PR DESCRIPTION
**Pull request by akofink**
I'm not sure why we're not running tests on this project, but they do exist. ~~I expect this PR to have 3 failures, 1 error.~~

### CODE REVIEW

**Comment by akofink** [comment]
I guess those tests were only failing on my local system. Still, they weren't being run on Travis builds by default.

**Comment by akofink** [comment]
@komidore64 Did you know hammer-cli-katello hasn't been running tests in Travis?

**Comment by stbenjam** [comment]
Haha wow :open_mouth: 

I can't merge but it looks good to me.  Paging @Katello/cli

**Comment by komidore64** [comment]
oh man. nice. :beer:

ACK

**Comment by komidore64** [comment]
@akofink ytm :boom: :boom:

**Pull request merged**
