### PR TITLE
Refs #33783 - bindings for org cdn configurator

### PR DESCRIPTION
**Pull request by parthaa**

### CODE REVIEW

**Comment by parthaa** [comment]
```bash

$ hammer organization configure-cdn --id=4 --password=<pass>--ssl-ca-credential-id=1 --upstream-organization-label=export-23660
 --url="https://example.com" --username=admin

Updated CDN configuration.


$ hammer organization info --id=4
.....

CDN configuration:      
    URL:                   https://example.com
    Upstream Organization: export-23660
    Username:              admin
    SSL CA Credential ID:  1
```

**Comment by parthaa** [comment]
Depends on https://github.com/Katello/katello/pull/8821

**Comment by jturel** [comment]
This all works well. Only thing I'd recommend changing is to remove the Red Hat Repository Url in organization show, since that's superceded by the cdn configuration now. i've left that field in the API for now, but can remove it in a few releases

**Comment by parthaa** [comment]
> This all works well. Only thing I'd recommend changing is to remove the Red Hat Repository Url in organization show, since that's superceded by the cdn configuration now. i've left that field in the API for now, but can remove it in a few releases

updated

**Review by jturel — APPROVED** [review]
ACK

**Comment by chris1984** [comment]
Test failures are unrelated, merging and will submit a pr to fix tests

**Pull request merged**
