### PR TITLE
fixes #12930 - send content view version id correctly

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by komidore64** [comment]
ACK

wow bravo

**Comment by stbenjam** [comment]
@komidore64 Plz2merge? I'm not on @Katello/cli team

please

**Comment by stbenjam** [comment]
thanks

**Comment by daviddavis** [comment]
@stbenjam [image thief](https://github.com/Catello/catello/issues/8).

**Comment by stbenjam** [comment]
@daviddavis 

bird-thief-o

**Pull request merged**
