### PR TITLE
[WIP] Fixes #25775 - create content view if it doesn't exist

### PR DESCRIPTION
**Pull request by beav**
Previously, the content view had to be created ahead of time before
content view versions were imported.

This patch creates the content view if it doesn't already exist. Note
that it only creates the CV with name and repos, it does not do
activation keys. Composites are handled as well.

### CODE REVIEW

**Comment by akofink** [comment]
WIP for tests only, or are you adding more code?

**Comment by beav** [comment]
> WIP for tests only, or are you adding more code?

tests and I want to move `find_library_repo` to import export helper.

**Comment by akofink** [comment]
:hammer:

**Comment by akofink** [comment]
Still working, or should we close this as stale?

**Comment by chris1984** [comment]
@akofink ill close this one and cherrypick his pr so he gets credit for it, it is still an rfe that needs to be addressed. Beav said I could take it over

**Pull request closed without merging**
