### PR TITLE
Cherry picks 3.2.1

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by akofink** [comment]
You will need https://github.com/Katello/hammer-cli-katello/pull/468 for passing tests.

**Comment by ehelms** [comment]
@akofink even though it fixes tests, this branch is part of 1.13/3.2 where the hammer is older, I suspect if we keep the test fixing commit in here it will break in production

**Comment by akofink** [comment]
@ehelms Yes, it must be paired with https://github.com/theforeman/hammer-cli/pull/227

**Comment by ehelms** [comment]
I'd recommend pulling that comment and accepting that tests will not run on this branch.

**Comment by johnpmitsch** [comment]
@ehelms its back to the 2 cherry picks and the version bump

**Pull request merged**
