### PR TITLE
Fixes #12713 - Fix bad manfiest class names

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by komidore64** [comment]
you don't like manfiests?

**Comment by jmrodri** [comment]
Did you create your redmine issue? Did you fill out Form 9528 in triplicate?

**Comment by daviddavis** [comment]
@jmrodri in quadruplicate.

@komidore64 any idea on these spec errors for hammer_cli_katello?

**Comment by komidore64** [comment]
ACK, we don't need manfiests anymore.

**Pull request merged**
