### PR TITLE
Fixes #7451 - Review whitespace in extracted strings

### PR DESCRIPTION
**Pull request by ofedoren**
depends on https://github.com/theforeman/hammer-cli/pull/265

### CODE REVIEW

**Comment by tstrachota** [comment]
It's nice job with fixing all the punctuation that @ofedoren did. I wrote couple of tests that should help with keeping the consistency for the future. @akofink you can consider adding it to `hammer-cli-katello` too.
See: https://github.com/theforeman/hammer-cli/pull/266 and https://github.com/theforeman/hammer-cli-foreman/pull/352

**Comment by mmoll** [comment]
@ofedoren this needs a rebase

**Comment by ofedoren** [comment]
@mmoll Done. But now it seems there is no actual need in this PR, because @akofink did needed changes in https://github.com/Katello/hammer-cli-katello/pull/541

**Comment by mmoll** [comment]
I guess a test like the one in theforeman/hammer-cli-foreman#352 could be added here which would help to prevent bad strings in the future.

**Comment by akofink** [comment]
@ofedoren Most of the tests in hammer-cli-katello use `'foo'.include?(test_string)`, so it's not really checking for formatting. I was thinking (a bit off topic for this PR) it'd be nice to have a test helper that removes capital letters and punctuation to help with matching expected messages in tests without failing on format. I agree with @mmoll that a distinct test for message format would be preferred, as we want tests to fail when the thing they're testing fails and not something unrelated.

**Comment by ofedoren** [comment]
Updated.

I've added the test @mmoll suggested and fixed other strings, but now this PR depends on https://github.com/theforeman/hammer-cli-foreman-tasks/pull/34 and https://github.com/Katello/katello/pull/7190

**Comment by akofink** [comment]
Sorry for not getting back to this. Could you rebase with master please?

**Comment by ofedoren** [comment]
@akofink done

**Comment by akofink** [comment]
I'm looking into these build failures. They're not (at least all) related to this PR. :)

**Comment by akofink** [comment]
Could you please rebase? The tests should be green afterwards.

**Comment by akofink** [comment]
It's going to need another rebase after https://github.com/Katello/hammer-cli-katello/pull/559 is merged in, which fixes the tests on master.

**Comment by beav** [comment]
@akofink is this PR ready to rock at this point?

**Pull request merged**
