### PR TITLE
Fixes #16457 - Support large file uploads

### PR DESCRIPTION
**Pull request by ehelms**
Changes to make use of new API param 'uploads' for passing
information Pulp requires for file uploads.

### CODE REVIEW

**Comment by daviddavis** [comment]
Tested and it worked with both file and rpm repos.

APJ

**Comment by ehelms** [comment]
@daviddavis note I had to do some re-factoring due to method length

**Comment by daviddavis** [comment]
Tested it again and it still seems to work. Code looks good.

APT

**Comment by ehelms** [comment]
@daviddavis made some test updates if you want to double check them

**Comment by daviddavis** [comment]
LGTM

**Pull request merged**
