### PR TITLE
Refs #13904 - moving content host register to host subscriptions

### PR DESCRIPTION
**Pull request by jlsherrill**
also moving LifecycleEnvironmentNameResolvable to KatelloEnvironmentNameResolvable

### CODE REVIEW

**Comment by ehelms** [comment]
Now that we have a test setup, what do you think about adding some for these updates?

**Comment by jlsherrill** [comment]
Totally will if whenever we decide on https://github.com/Katello/katello/pull/5831

**Comment by jlsherrill** [comment]
@ehelms updated for PR changes and added tests :dollar:   :dollar:   :dollar:

**Comment by thomasmckay** [comment]
ACK

**Pull request merged**
