### PR TITLE
Fixes #14007 - Typo in MissingSeachOptions

### PR DESCRIPTION
**Pull request by zjhuntin**
Adds hammer-foreman repo.

### CODE REVIEW

**Comment by beav** [comment]
ACK

**Comment by komidore64** [comment]
Would you explain why we're locking down to ``hammer_cli_foreman`` master?

**Comment by jlsherrill** [comment]
@komidore64 right now travis is running tests off the latest release of hammer_cli_foreman, while the nightly bats tests are using nightly builds.  So we are in a situation where hammer_cli_katello master isn't compatible with hammer_cli_foreman master, nor is hammer in katello nightly repos compatible with hammer in the foreman nightly repos.  

 I think in addition to this we should move to building hammer as a nightly release similar to foreman

**Comment by komidore64** [comment]
who needs versions amirite?

**Comment by zjhuntin** [comment]
Thanks @komidore64 and @ranjan!

**Comment by beav** [comment]
I would be :+1: for combining some of the hammer repos, if they are tightly dependent on each other.

**Pull request merged**
