### PR TITLE
Fixes #15305 - Add readme for generating API data

### PR DESCRIPTION
**Pull request by akofink**

### CODE REVIEW

**Comment by ehelms** [comment]
I'm not sure I'd think to look in test/data for separate README.

**Comment by akofink** [comment]
@ehelms This is modeled after [hammer-cli-foreman's documentation](https://github.com/theforeman/hammer-cli-foreman/blob/master/test/data/README.md) for generating the test API. They also have a separate Readme in `./locale/`.

If you think it's hard to find, what if we link to this Readme from the main project Readme?

**Comment by ehelms** [comment]
Sure.

**Comment by ehelms** [comment]
ACK - thanks @akofink

**Pull request merged**
