### PR TITLE
Fixes #16533 - Show package applicability for hosts

### PR DESCRIPTION
**Pull request by daviddavis**
https://github.com/Katello/katello/pull/6313

### CODE REVIEW

**Comment by akofink** [comment]
Actually, before you merge, is there a Katello API change associated with this? I'm not seeing those two parameters anywhere in the API.

**Comment by daviddavis** [comment]
@akofink sorry, forgot to mention that this requires https://github.com/Katello/katello/pull/6313.

**Comment by akofink** [comment]
Please update test/data/3.2/foreman_api.json to reflect the API change

**Comment by daviddavis** [comment]
@akofink updated foreman_api.json, added a test, and merged the required api PR.

**Comment by akofink** [comment]
LGTM!

**Pull request merged**
