### PR TITLE
Refs #12556 - remove system subcommand

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by akofink** [comment]
What about https://github.com/Katello/hammer-cli-katello/blob/edafb34667e01c6ff9eac4489c2feb6fec081b35/lib/hammer_cli_katello/subscription.rb#L8

**Comment by jlsherrill** [comment]
@akofink what about it?  :) 

That's not related to the removal of systems, unless i'm misunderstanding what you mean.

**Comment by akofink** [comment]
@jlsherrill And this https://github.com/Katello/hammer-cli-katello/blob/e3a6acb8ca068288eee1cf8b2b89842d168d7d6e/lib/hammer_cli_katello/id_resolver.rb#L63

I don't think the `:systems` resource exists anymore, so any reference to it will cause NoMethodError on nil.

**Comment by akofink** [comment]
@jlsherrill Is this the PR to fix any hammer issues caused by the host unification Katello PR?

**Comment by akofink** [comment]
You should rebuild the apipie-cache and put it on this PR - some of the test failures will point out other uses of the systems resource.

**Comment by jlsherrill** [comment]
@akofink the 'broken' command is tracked here: http://projects.theforeman.org/issues/14403

This is simply the PR to remove all uses of the systems controller  (/katello//api/v2/systems/)

**Comment by jlsherrill** [comment]
Will do!

**Comment by jlsherrill** [comment]
@akofink added!

**Comment by akofink** [comment]
Looks good. ACK Thanks @jlsherrill!

**Pull request merged**
