### PR TITLE
fixes #12350 - content_view - add copy command

### PR DESCRIPTION
**Pull request by bbuckingham**
This is to add copy command to be consistent with UI behaviors.

### CODE REVIEW

**Comment by komidore64** [comment]
this looks good to me.

would someone with a working dev env smoke test this real quick?

**Comment by ehelms** [comment]
This seems to be requiring both `id` and `name` which I assume `name` here is the name of the new content view. However, the help text indicates it is there for searching:

```
 --name NAME                             Content view name to search by
```

**Comment by bbuckingham** [comment]
@ehelms, updated so that the help text now shows: 

```
 --name NAME                             New content view name
```

**Comment by ehelms** [comment]
ACK

**Pull request merged**
