### PR TITLE
Katello 3.11 Cherry-picks

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by akofink** [comment]
Actually, I think this should go in the next release, 0.17.0

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
@akofink thanks for looking! There looks to be at least one change on master slated for 3.12 so that's why I cherry-picked. Does 0.17 still seem appropriate? 

ex: https://github.com/Katello/hammer-cli-katello/commit/1fad5382de0e166cc570fe17e3fd9f64c6d813fa

**Comment by akofink** [comment]
Yes - 0.16.z is for Katello 3.10. I think we should move #25845 to 3.11, hammer-cli-katello 0.17.z.

**Comment by jturel** [comment]
That works for me. I've moved it in Redmine & I'll close this PR. Can you cut a release then & I'll take care of the packaging side?

**Pull request closed without merging**
