### PR TITLE
Refs #14196 - support host subscription unsubscribe

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note that tests are currently busted, trying to figure out what is wrong with the foreman_api.json loading

**Comment by jlsherrill** [comment]
Updated tests

**Comment by cfouant** [comment]
@jlsherrill - this doesn't seem to work when the `--host` option is used and there is more than one host registered to the system.
```
[vagrant@centos7-devel hammer-cli-katello{unregister}]$ hammer host list
---|-----------------------|------------------|------------|-----------------|------------------
ID | NAME                  | OPERATING SYSTEM | HOST GROUP | IP              | MAC              
---|-----------------------|------------------|------------|-----------------|------------------
3  | otherrhel.example.com | RedHat 7.1       |            | 192.168.121.195 | 52:54:00:40:18:a6
4  | rhel7.example.com     | RedHat 7.2       |            | 192.168.121.33  | 52:54:00:78:26:ad
---|-----------------------|------------------|------------|-----------------|------------------
[vagrant@centos7-devel hammer-cli-katello{unregister}]$ hammer host subscription unregister --host otherrhel.example.com
Could not unregister the host:
  Error: found more than one host
```

**Comment by jlsherrill** [comment]
@cfouant updated

**Comment by jlsherrill** [comment]
opened http://projects.theforeman.org/issues/14307 to make id resolving consistent

**Comment by cfouant** [comment]
Works for me now APT

**Comment by jlsherrill** [comment]
[test]

**Pull request merged**
