### PR TITLE
Fixes #11802 : Pull in the downstream strings.

### PR DESCRIPTION
**Pull request by bkearney**
There is no comparison link, since this package is not yet
    moved to transifex. This pull request requires that
    https://github.com/Katello/hammer-cli-katello/pull/315 in order to test it.

### CODE REVIEW

**Comment by ehelms** [comment]
Please rebase now thta #315 is in

**Comment by bkearney** [comment]
@ehelms rebased

**Comment by ehelms** [comment]
Looking at the format of the english file compared to the rest, is there a reason it is different? e.g. not broken down by files, missing some header information

**Comment by bkearney** [comment]
@ehelms however the engish file was originally generated it kept all the source locations for the strings. This caused alot of changes which are showing as deletes. The other files are all new.

**Comment by bkearney** [comment]
@ehelms rebased this again.

**Comment by ehelms** [comment]
ACK

**Pull request merged**
