### PR TITLE
Add ci_reporter_minitest to Gemfile and match h-c-f more closely

### PR DESCRIPTION
**Pull request by ianballou**
Should fix the issue in nightly: `[2024-05-07T19:54:51.653Z] Don't know how to build task 'ci:setup:minitest' (see --tasks)`

Also made some updates to better match https://github.com/theforeman/hammer-cli-foreman/blob/master/Gemfile

### CODE REVIEW

**Review by chris1984 — CHANGES_REQUESTED** [review]
A rubocop failure and are those test failures related?

**Comment by ianballou** [comment]
I upgraded mini test, this might be the fallout from that. I'll take a look into what needs fixing.

**Comment by ianballou** [comment]
I needed to remove the use of `let(:name)` due to:

```
/home/vagrant/hammer-cli-katello/.vendor/ruby/3.0.0/gems/minitest-5.22.3/lib/minitest/spec.rb:253:in `let': let 'name' cannot override a method in Minitest::Spec. Please use another name. (ArgumentError)
```

**Review by chris1984 — APPROVED** [review]
Looks good

**Pull request merged**
