### PR TITLE
Fixes #15589 - Remove content-host update command

### PR DESCRIPTION
**Pull request by akofink**
The new command is `hammer host update ...` which exists in hammer-cli-foreman/Foreman.

### CODE REVIEW

**Comment by bbuckingham** [comment]
This would be handled separate from this PR; however, are we tracking an issue to remove the update action from the Katello API ?   (ref: https://github.com/Katello/katello/blob/master/app/controllers/katello/api/v2/systems_controller.rb#L71)

**Comment by bbuckingham** [comment]
APT

**Comment by akofink** [comment]
Tests will be dependent on merging https://github.com/Katello/hammer-cli-katello/pull/417

**Comment by akofink** [comment]
[test]

**Pull request merged**
