### PR TITLE
Fixes #14466 - add support for Gemfile.local.rb

### PR DESCRIPTION
**Pull request by tstrachota**
The change keeps backward compatibility with `Gemfile.local`

### CODE REVIEW

**Comment by tstrachota** [comment]
@stbenjam since you filed the issue, would you mind reviewing the change, please? We've already got it merged in `hammer-cli` and `hammer-cli-foreman`

**Comment by akofink** [comment]
ACK

**Comment by stbenjam** [comment]
:+1: Looks good to me too

**Comment by tstrachota** [comment]
Thanks!

**Pull request merged**
