### PR TITLE
Fixes #10062 - Allow users to see repos for a content view

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by ehelms** [comment]
@daviddavis Does this require the API change first? And is this compatible with master or does it require the OS Tree work first?

**Comment by daviddavis** [comment]
The API change is right above your comment. It should work on master (without any ostree work). It'll show just a blank set for OSTree content. If that's a problem, I can wait until after ostree makes it to master to merge this.

**Comment by ehelms** [comment]
ACK

**Comment by daviddavis** [comment]
Opened new PR: https://github.com/Katello/hammer-cli-katello/pull/310

**Pull request closed without merging**
