### PR TITLE
Refs #3036 - Ping command

### PR DESCRIPTION
**Pull request by ofedoren**
requires https://github.com/theforeman/hammer-cli-foreman/pull/394 and https://github.com/Katello/katello/pull/7751 to be merged first

### CODE REVIEW

**Comment by evgeni** [comment]
The :policeman: complains:

```
lib/hammer_cli_katello/status.rb:20:101: C: Line is too long. [108/100]
  HammerCLIForeman::StatusCommand::ForemanCommand.extend_with(HammerCLIKatello::CommandExtensions::Ping.new)
                                                                                                    ^^^^^^^^
lib/hammer_cli_katello/ping.rb:61:101: C: Line is too long. [103/100]
          service['_response'] = HammerCLIKatello::CommandExtensions::Ping.get_server_response(service)
                                                                                                    ^^^
lib/hammer_cli_katello/ping.rb:74:101: C: Line is too long. [106/100]
  HammerCLIForeman::PingCommand::ForemanCommand.extend_with(HammerCLIKatello::CommandExtensions::Ping.new)
                                                                                                    ^^^^^^
```

@ofedoren could you please have a look? this is currently blocking the katello nightlies (cc @tbrisker) as they test for `hammer ping`

**Comment by ofedoren** [comment]
@evgeni, done.

**Comment by ofedoren** [comment]
If we want to avoid another PR related to `ping` command wait for https://github.com/Katello/katello/pull/8386 :)

**Comment by mbacovsky** [comment]
The related hammer-cli-foreman PR was merged finally. I tested it also with the https://github.com/Katello/katello/pull/8386 and it works as expected. 

@ofedoren are there any other changes needed besides updating the tests if the Katello PR is merged?

**Comment by ofedoren** [comment]
@mbacovsky, no. Since Foreman/Katello PRs are going to be merged, I'm going to update this PR today accordingly, then it's ready.

**Comment by ofedoren** [comment]
The PR is updated and now requires https://github.com/Katello/katello/pull/8386.

**Comment by chris1984** [comment]
Thanks @ofedoren tests are green and the Katello PR is merged :)

**Pull request merged**
