### PR TITLE
Refs #31734 - Hammer endpoints for enable/disable

### PR DESCRIPTION
**Pull request by parthaa**

### CODE REVIEW

**Comment by parthaa** [comment]
Connected to https://github.com/Katello/katello/pull/9117
```
hammer simple-content-access enable --organization-id=1
hammer simple-content-access disable --organization-id=1
```

**Review by chris1984 — APPROVED** [review]
ACK, works good:

```bash
[root@nightly ~]# hammer simple-content-access enable --organization-id 1
Simple Content Access Enabled.
```

Screenshot of task:

https://1drv.ms/u/s!AmcYeL73Lgj6hQGBA9xyvleJyfQk?e=MHJKSr

```bash
[root@nightly ~]# hammer simple-content-access enable --organization-id 1
Simple Content Access Disabled.
```

Screenshot of task:

https://1drv.ms/u/s!AmcYeL73Lgj6hQJtYqoHBfeeEpnh?e=HtIavb

**Comment by chris1984** [comment]
@parthaa do you think we should have a command for eligible too?

**Comment by parthaa** [comment]
Added the eligibility checks
Org 1 had manifest while org 3 did not

```
$ hammer simple-content-access enable --organization-id=3
Could not enable Simple Content Access for this organization:
  Current organization has no manifest imported.

$ hammer simple-content-access disable --organization-id=3
Could not disable Simple Content Access for this organization:
  Current organization has no manifest imported.

$ hammer simple-content-access enable --organization-id=1
Simple Content Access Enabled.

$ hammer simple-content-access disable --organization-id=1
Simple Content Access Disabled.
```

**Pull request merged**
