### PR TITLE
Refs #32000 - Remove legacy export/import commands

### PR DESCRIPTION
**Pull request by chris1984**
Katello PR: https://github.com/Katello/katello/pull/9203

### CODE REVIEW

**Comment by jturel** [comment]
Ordinarily I'd be :-1:  to including the API JSON + test updates since they are unrelated to your PR (I think...) but I don't think this is going to get cherry-picked into any other hammer release which would get ugly. At a minimum I'd have liked to see a separate issue # for the JSON+test update in the commit which avoids a hypothetical cherry-picking problem. Anyway, LGTM :)

**Review by jturel — APPROVED** [review]
ACK

**Comment by chris1984** [comment]
@jturel I will make a seperate issue and break them out so this pr is just the removal of the commands.

**Comment by jturel** [comment]
merge it :)

**Pull request merged**
