### PR TITLE
Fixes #14439 - Support incremental update without lifecycle environments

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Requires https://github.com/Katello/katello/pull/5931

**Comment by bbuckingham** [comment]
@jlsherrill, I tried a couple of scenarios, but the results were not what I expected.  The setup was:
- composite with 2 components (1-yum, 1-puppet) - version published to 'dev' needs an update on the 'yum' component
- performing an incremental update on the yum version (1.0) needing the update and attempting to propagate to the composite
- client registered to composite version on dev env

```
hammer> content-view version incremental-update --organization-id 1 --content-view-version "1.0"  --errata-ids RHEA-2012:0002 --propagate-all-composites true
An error occurred incrementally updating the content view:
  Error: found more than one lifecycle_environment

hammer> content-view version incremental-update --organization-id 1 --content-view-version-id 13  --errata-ids RHEA-2012:0002 --propagate-all-composites true
An error occurred incrementally updating the content view:
  Error: undefined method `include?' for nil:NilClass
hammer> 
```

For the second case, the following was the stack: http://fpaste.org/355149/46057427/

**Comment by bbuckingham** [comment]
@jlsherrill, I tested this PR combined with the https://github.com/Katello/hammer-cli-katello/pull/378 and get slightly different results.  One thing to be aware of is that content view version 13 which is part of the composite, is not in any environment.

```
hammer> content-view version incremental-update --organization-id 1 --content-view-version "1.0"  --errata-ids RHEA-2012:0002 --propagate-all-composites true
An error occurred incrementally updating the content view:
  Error: found more than one content_view_version

hammer> content-view version incremental-update --organization-id 1 --content-view-version-id 13  --errata-ids RHEA-2012:0002 --propagate-all-composites true
An error occurred incrementally updating the content view:
  Error: Could not find lifecycle_environment. Some search options were missing, please see --help.
hammer> 
```

**Comment by bbuckingham** [comment]
Update... It looks like there were changes to either hammer-cli or hammer-cli-foreman that impact the scenario.   The following is an updated scenario:

```
hammer> content-view version incremental-update --organization-id 1 --content-view-version "1.0"  --errata-ids RHEA-2012:0002 --propagate-all-composites true
An error occurred incrementally updating the content view:
  Error: found more than one content_view_version

hammer> content-view version incremental-update --organization-id 1 --content-view-version-id 13  --errata-ids RHEA-2012:0002 --propagate-all-composites true
[.........................................................................................................................................] [100%]
Content View: zoo view version 1.6
Added Content:
  Errata:
        RHEA-2012:0002
  Packages:
        penguin-0.9.1-1.noarch
        shark-0.1-1.noarch
        walrus-5.21-1.noarch

Content View: composite version 2.4
Added Content:

hammer> 
```

As can be seen by the output, incremental-update by version string (e.g. '1.0') fails; however, by id (e.g. 13) works.  In chatting w/ @jlsherrill a separate bug will be created to address that first failure.

Based on the above ACK to getting this improvement merged.

**Comment by jlsherrill** [comment]
Opened http://projects.theforeman.org/issues/14649  for the --content-view-version issue.

Thanks @bbuckingham !

**Pull request merged**
