### PR TITLE
Fixes #11801 : Update the version of gettext, and modify the rake file.

### PR DESCRIPTION
**Pull request by bkearney**
This brings hammer-cli-katello in line with hammer-cli. Also, it would be
good to get this tool into transifex like the other hammer plugins.

### CODE REVIEW

**Comment by ehelms** [comment]
@bkearney looks like this needs an update

**Comment by bkearney** [comment]
@ehelms fixed

**Comment by ehelms** [comment]
I think you may need to rebase this as I am seeing two commits

**Comment by bkearney** [comment]
@ehelms fixed

**Comment by ehelms** [comment]
ACK

**Pull request merged**
