### PR TITLE
Refs #14336 - fixes update-all-hosts for inc update

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by bbuckingham** [comment]
Below is the incremental-update --help.  
- should --environments be --lifecycle-environments?
- should both --update-all-hosts and --update-all-systems be listed?
- --errata-ids mentions uuids, should that be updated to reflect the expanded behavior of uuid, id and advisory id?

```
hammer> content-view version incremental-update --help
Usage:
     content-view version incremental-update [OPTIONS]

Options:
 --async                                             Do not wait for the task
 --content-view-version CONTENT_VIEW_VERSION_VERSION Content view version number
 --content-view-version-id CONTENT_VIEW_VERSION_ID   Content view version identifier
 --description DESCRIPTION                           The description for the new generated Content View Versions
 --environments ENVIRONMENT_NAMES                    Comma separated list of values.
 --errata-ids ERRATA_IDS                             Errata uuids to copy into the new versions.
                                                     Comma separated list of values.
 --host-ids HOST_IDS                                 IDs of hosts to update
                                                     Comma separated list of values.
 --lifecycle-environment-ids ENVIRONMENT_IDS         list of lifecycle environment IDs to update the content view version in
                                                     Comma separated list of values.
 --package-ids PACKAGE_IDS                           Package uuids to copy into the new versions.
                                                     Comma separated list of values.
 --packages PACKAGE_NAMES                            Comma separated list of values.
 --propagate-all-composites PROPAGATE_ALL_COMPOSITES If true, will publish a new composite version using any specified content_view_version_id that has been promoted to a lifecycle environment.
                                                     One of true/false, yes/no, 1/0.
 --puppet-module-ids PUPPET_MODULE_IDS               Puppet Modules to copy into the new versions.
                                                     Comma separated list of values.
 --puppet-modules PUPPET_MODULE_NAMES                Comma separated list of values.
 --resolve-dependencies RESOLVE_DEPENDENCIES         If true, when adding the specified errata or packages, any needed dependencies will be copied as well.
                                                     One of true/false, yes/no, 1/0.
 --search SEARCH                                     Search string for systems to perform an action on
 --update-all-hosts UPDATE                           Update all editable and applicable hosts within the specified Content View and \
                                                               Lifecycle Environments
                                                     One of true/false, yes/no, 1/0.
 --update-all-systems UPDATE_ALL_SYSTEMS             Update all editable and applicable systems, not just ones using the selected Content View Versions and Environments
                                                     One of true/false, yes/no, 1/0.
 -h, --help                                          print help
```

**Comment by bbuckingham** [comment]
The following is not directly related to these changes, but appears to be part of the incremental-update workflow:

```
hammer> content-host available-incremental-updates --id 1
Error: undefined method `resource' for HammerCLIKatello::ContentHostCommand:Class
hammer> 
```

**Comment by jlsherrill** [comment]
@bbuckingham fixed the --environments showing up, the uuid messages are fixed in the api docs here:  https://github.com/Katello/katello/pull/5916

opened http://projects.theforeman.org/issues/14403 for the available-incremental-updates command issue

**Comment by bbuckingham** [comment]
@jlsherrill, Thanks for the updates.  One minor comment, with the changes, it appears that we would lose the ability to specify lifecycle-environments by name.  If possible, we need to continue to support that.

**Comment by jlsherrill** [comment]
@bbuckingham updated to support that

**Comment by bbuckingham** [comment]
@jlsherrill, Tested and it worked well.  The code and tests look good.  Thanks!   ACK

Note: This PR was tested using the fixes available in https://github.com/Katello/katello/pull/5916 and the referenced pulp fix.

**Pull request merged**
