### PR TITLE
Fixes #18346 - support displaying containerver var

### PR DESCRIPTION
**Pull request by jlsherrill**
when listing repository sets that contain that variable

Requires: https://github.com/Katello/katello/pull/6606

### CODE REVIEW

**Comment by jlsherrill** [comment]
The workflow:

```
hammer repository-set list --product='Red Hat Container Images'  --organization=oriontest
hammer repository-set available-repositories  --product='Red Hat Container Images'  --organization=oriontest --name='Red Hat Enterprise Linux 7 for Containers (RPMs)'
hammer repository-set enable  --product='Red Hat Container Images'  --organization=oriontest --name='Red Hat Enterprise Linux 7 for Containers (RPMs)' --containerver=7.4   --basearch=x86_6
hammer repository-set available-repositories  --product='Red Hat Container Images'  --organization=oriontest --name='Red Hat Enterprise Linux 7 for Containers (RPMs)'
```

**Comment by johnpmitsch** [comment]
@akofink can you assign me as a reviewer? I don't have permissions

**Comment by akofink** [comment]
@johnpmitsch I think you have to be in the CLI team to be a reviewer.

**Comment by akofink** [comment]
@jlsherrill Could you give some info on why this was closed?

**Pull request closed without merging**
