### PR TITLE
Fixes #33134 - Fix command extensions and tests

### PR DESCRIPTION
**Pull request by ofedoren**
Requires/follows https://github.com/theforeman/hammer-cli-foreman/pull/580.

### CODE REVIEW

**Comment by ofedoren** [comment]
[test]

**Comment by ofedoren** [comment]
@chris1984, if you want to make tests green in development, it's ready now :) Mentioned PRs were merged (available only on master/nightly).

**Comment by chris1984** [comment]
@ofedoren sure I will take a look and we can get this merged.

**Review by chris1984 — APPROVED** [review]
ACK, works good and tests are passing

**Pull request merged**
