### PR TITLE
Refs #12673 - Filter Rules now show date type

### PR DESCRIPTION
**Pull request by parthaa**
$ hammer content-view filter rule info --id=1 --content-view-filter-id=2
Rule ID:   1
Filter ID: 2
Date Type: updated
Types:     security, enhancement, bugfix
Created:   2015/12/11 22:21:43
Updated:   2015/12/11 22:21:43

### CODE REVIEW

**Comment by parthaa** [comment]
connected to https://github.com/Katello/katello/pull/5651

**Comment by komidore64** [comment]
ACK

**Comment by komidore64** [comment]
i'm assuming you want to wait until after Katello/katello#5651 is merged?

**Comment by parthaa** [comment]
@komidore64 5651 got merged .. So going to merge this.

**Comment by komidore64** [comment]
thanks @parthaa :+1:

**Pull request merged**
