### PR TITLE
Fixes #29033 - added usergroups to search option creators

### PR DESCRIPTION
**Pull request by yifatmakias**

### CODE REVIEW

**Comment by yifatmakias** [comment]
This PR is related to the following PR:
https://github.com/theforeman/hammer-cli-foreman/pull/501

**Comment by yifatmakias** [comment]
@chris1984 Hi :)
Can you please explain to me why the tests above failed? Is there something I need to change or fix in my code?

**Comment by yifatmakias** [comment]
I added a test, let me know if it is ok.

**Comment by akofink** [comment]
The 3 test failures are unrelated to this change.

**Comment by ofedoren** [comment]
@akofink, FYI https://github.com/theforeman/hammer-cli-foreman/pull/501 was merged.

**Comment by chris1984** [comment]
@akofink i rekicked travis and all green now :)

**Pull request merged**
