### PR TITLE
Fixes #14007 - Typo in MissingSeachOptions

### PR DESCRIPTION
**Pull request by ranjan**
It depends on [theforeman/hammer-cli-foreman#238](https://github.com/theforeman/hammer-cli-foreman/pull/238)

### CODE REVIEW

**Comment by adamruzicka** [comment]
Looks good to me

**Comment by adamruzicka** [comment]
[test]

**Comment by jlsherrill** [comment]
I think we need a release of hammer_cli_foreman before these tests will pass

**Comment by jlsherrill** [comment]
Closing in favor of this PR https://github.com/Katello/hammer-cli-katello/pull/400  which includes your commit.

Thanks @ranjan !

**Pull request closed without merging**
