### PR TITLE
Refs #22253 - Fixes after option validation is mixed with sources

### PR DESCRIPTION
**Pull request by tstrachota**
This patch makes hammer-cli-katello compatible with changes in:
https://github.com/theforeman/hammer-cli/pull/242 and https://github.com/theforeman/hammer-cli-foreman/pull/402

Please see the discussion in the PR into hammer core for more details about the functionality that is going to be merged there.

### CODE REVIEW

**Comment by mbacovsky** [comment]
@akofink, thanks for looking at this! The PRs in core and hammer-cli-foreman are approved and can be merged if you are okay with it.

**Comment by akofink** [comment]
There are [rubocop issues](https://travis-ci.org/Katello/hammer-cli-katello/jobs/467999548#L614) with this PR that need to be resolved. I'm fine to merge hammer-cli and hammer-cli-foreman PRs.

**Comment by akofink** [comment]
This PR is blocking others on the project because the build fails without it. I'd appreciate it if we could get this green quickly.

**Comment by tstrachota** [comment]
@akofink @mbacovsky rubocop issues fixed

**Pull request merged**
