### PR TITLE
Fixes #31052 - Add cvv export-histories command and test

### PR DESCRIPTION
**Pull request by chris1984**
@parthaa here is the export-histories

### CODE REVIEW

**Comment by chris1984** [comment]
output looks like:
```shell
[vagrant@centos7-hammer-devel hammer-cli-katello]$ hammer content-view version export-histories
---|--------------------|--------------------------------------------------------------------------------|----------------------|-------------------------|-------------------------|------------------------
ID | DESTINATION SERVER | PATH                                                                           | CONTENT VIEW VERSION | CONTENT VIEW VERSION ID | CREATED AT              | UPDATED AT             
---|--------------------|--------------------------------------------------------------------------------|----------------------|-------------------------|-------------------------|------------------------
1  | tascioni           | /var/lib/pulp/exports/export-22589/view/1.0/tascioni/2020-10-08T16-52-47-00-00 | view 1.0             | 3                       | 2020-10-08 16:52:49 UTC | 2020-10-08 16:52:49 UTC
---|--------------------|--------------------------------------------------------------------------------|----------------------|-------------------------|-------------------------|------------------------
```

**Comment by chris1984** [comment]
Test failure is unrelated, looks like something changed in Foreman with the new API data included in this PR. Will make an issue and pr to fix the foreman test failure.

**Comment by chris1984** [comment]
Needs this guy for green tests:

https://github.com/Katello/hammer-cli-katello/pull/748, whoever reviews this if you can ack that pr.

**Comment by parthaa** [comment]
Tested works well . APJ

**Review by parthaa — APPROVED** [review]
apj

**Pull request merged**
