### PR TITLE
Fixes #14146 - ActivationKey Info clarified.

### PR DESCRIPTION
**Pull request by zjhuntin**
To replicate have an activation key associated with default organization. Do hammer activation-key info --id [id of Activation Key].

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test]

**Comment by ehelms** [comment]
Looks like you have two commits here now from merging in master to your branch.

**Comment by zjhuntin** [comment]
Ahh, didn't realize it would do that, I'll fix it.

**Comment by zjhuntin** [comment]
Okay, fixed.

**Comment by bbuckingham** [comment]
@zjhuntin, For consistency with the UI, you may also want to change 'Consumed' on the List command to use 'Host Limit'.

**Comment by bbuckingham** [comment]
@zjhuntin, Unfortunately, looks like it will need a rebase with master to become mergeable as well.

**Comment by bbuckingham** [comment]
@zjhuntin, Also, for awareness, you have 'fixes' on both this PR and https://github.com/Katello/katello/pull/5871 using the same redmine issue.  This means that as soon as one of them is merged, the issue will get closed.  Generally, you may want to use 'refs' on one and 'fixes' on the other. In addition, within the PR, include a reference to the other PR.  This will help reviewers know that there are multiple PRs covering the complete fix.

**Comment by zjhuntin** [comment]
@bbuckingham Will do next time, thanks for the heads up on that. I will go ahead and change Consumed on the list command and rebase it.

**Comment by bbuckingham** [comment]
ACK.  Merging.

Thanks @zjhuntin !

**Pull request merged**
