### PR TITLE
Bump to 0.21.0 for Katello 3.15

### PR DESCRIPTION
**Pull request by jturel**
Seeing if this builds before branching.

### CODE REVIEW

**Comment by akofink** [comment]
You'll also probably need to include the updated Katello 3.15 apipie cache.

**Comment by jturel** [comment]
> The base should be 0.21.z, not master. master should get bumped to `0.22-master`. I've just created the 0.21.z branch from master for you.

Yeah, I just wanted to see if the tests would run

**Comment by jturel** [comment]
Thanks for pushing the branch!

**Comment by jturel** [comment]
[test]

**Comment by jturel** [comment]
@akofink any sense of these failures? I don't mind fixing them but need a better idea. Do they look like real failures or could something else be broken?

**Comment by akofink** [comment]
I'm not exactly sure, but it seems like something wrong with the versions of hammer_cli and/or hammer_cli_foreman. I'd try running with master versions of all 3, and if it fails, try the latest release of all 3, then use git bisect to figure out when it broke. I think @chris1984 was going to figure out the broken tests on master here.

**Comment by jturel** [comment]
This will be green once there's a new release of hammer-cli-foreman (probably 2.0.1)

**Comment by ekohl** [comment]
Just linking https://github.com/theforeman/hammer-cli-foreman/pull/504 for completeness

**Comment by jturel** [comment]
@akofink @chris1984 green!

**Pull request merged**
