### PR TITLE
Fixes #34337 - CRUD simplified ACSs via hammer

### PR DESCRIPTION
**Pull request by ianballou**
Adds support for showing products, and removes some unnecessary smart proxy params.

Katello PR: https://github.com/Katello/katello/pull/10172

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
ACK, looks good

**Comment by sjha4** [comment]
The `hammer alternate-content-sources create` is plural whereas we use singular in most cases for commands.

**Comment by sjha4** [comment]
Don't know if I am missing something but the organization params seem to not have been included for acs.

[vagrant@centos7-hammer-devel2 hammer-cli-katello]$ hammer alternate-content-sources create --alternate-content-source-type=simplified --content-type=yum --product-names=["custom"] --organization-id=1
Could not create the Alternate Content Source.:
  Error: Unrecognised option '--organization-id'.

**Comment by ianballou** [comment]
@sjha4 @chris1984 is this good to merge? The API work is done.  I think everything here should still be set.

**Comment by chris1984** [comment]
Lets ship it

**Comment by ianballou** [comment]
Someone will need to merge for me

**Pull request merged**
