### PR TITLE
fixes #11740 - sync plan - show enabled flag on list and show commands

### PR DESCRIPTION
**Pull request by bbuckingham**

### CODE REVIEW

**Comment by ehelms** [comment]
Looks like you need to rebase

**Comment by bbuckingham** [comment]
@ehelms, Rebased.

**Comment by rplevka** [comment]
@bbuckingham: FYI - there's already a pending PR addressing this issue: #312

**Comment by bbuckingham** [comment]
@rplevka, Thanks for the info.  In the future, please assign the bugzilla to yourself and move it to the ASSIGNED state when you begin working on it.    These are indicators that someone is actually working on it. :)

Also, if you create an upstream redmine for it, please also add that to the URL field of the bugzilla.

**Comment by bbuckingham** [comment]
closing in favor of https://github.com/Katello/hammer-cli-katello/pull/312

**Comment by rplevka** [comment]
@bbuckingham:
noted. Thanks for the suggestions.
Anyway - #312 addresses the issue different way. If you think, your solution is the correct one, feel free to re-open and close mine.

cheers.

**Comment by bbuckingham** [comment]
@rplevka, No, that is totally Ok.  I'd rather use your's, even if we make a minor tweak to it.  I did not mean to duplicate your effort and appreciate the contribution!  Please, let's continue with your's. :)

**Pull request closed without merging**
