### PR TITLE
Add host deb list

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by chris1984** [comment]
Will start to test

**Comment by chris1984** [comment]
@sbernhard do you have steps how to register a deb client to katello?

**Comment by sbernhard** [comment]
well :) you need to have a running sub-man on debian/ubuntu and register it then :) its not that easy. If you want, I can share a debian pkg for your test. Just let me know which OS you want to use.

**Comment by chris1984** [comment]
@sbernhard I can use Ubuntu 18.04

**Comment by chris1984** [comment]
Got the files :) Will start testing first thing tomorrow morning so we can get this pr into the next hammer release.

**Comment by sbernhard** [comment]
awesome. thank you! very appreciated!

**Pull request merged**
